### ISSUE TITLE
Can't build with pelican 4 or >

### ISSUE THREAD

**Issue by renich** [laughk/pelican-hss#55]
It seems you need to add `format(slug=...` to `templates/category.html`. 

https://github.com/gilsondev/pelican-clean-blog/pull/79

**Comment by laughk** [comment]
Thank you for your report. I'll fix it.

I haven't been able to notice this problem because I don't have "categories" enabled on my blog.

**Comment by laughk** [comment]
This issue has been fixed in v2.0.2. 

https://github.com/laughk/pelican-hss/releases/tag/v2.0.2
